### ISSUE TITLE
Dist version doesn't work in a web server

### ISSUE THREAD

**Issue by atropo** [fyodorio/ng-hotrod#6]
Thanks for this project, is very helpful.

After i build your code with `yarn build` or `npm run build`  I see the creation of the `dist/` directory with all the files minified.

If I serve that directory with a webserver using:

```bash
docker run -p 80:80 -v $(pwd):/usr/share/nginx/html nginx 
```
or the  [instant web server](https://www.npmjs.com/package/instant) with:

``` 
instant 8800  
```

The app won't work and in the console I see this error:

```js
09:58:05.732 angular.js:15570 Error: [$injector:unpr] Unknown provider: iProvider <- i
https://errors.angularjs.org/1.7.9/$injector/unpr?p0=iProvider%20%3C-%20i
    at angular.js:138
    at angular.js:4926
    at Object.u [as get] (angular.js:5086)
    at angular.js:4931
    at u (angular.js:5086)
    at c (angular.js:5111)
    at Object.invoke (angular.js:5135)
    at M.instance (angular.js:11707)
    at ot (angular.js:10520)
    at angular.js:9835
(anonymous) @ angular.js:15570
```

To me looks like there's a problem with the minification.

**Comment by fyodorio** [comment]
Thanks for reporting, @atropo, I'll get into it 👌

**Comment by fyodorio** [comment]
@atropo, can you provide your docker config please so that I could reproduce the issue in a more specific environment and make sure other types of environments are OK after that?

**Comment by fyodorio** [comment]
@atropo I'd tested the fix at different environments, please confirm that it works for you, in opposite case feel free to ping me to reopen the issue

**Comment by fyodorio** [comment]
For the sake of documenting the issue for others, though it's a rather unusual case these days - combining AngularJS applications with Parcel bundler and specific Babel plugins 🤷‍♂️

It was caused by failing minification resulting in `Unknown provider: iProvider <- i` console [error](https://code.angularjs.org/1.7.9/docs/error/$injector/unpr?p0=iProvider%20%3C-%20i). The reason for that is that `babel-plugin-angularjs-annotate` babel [plugin](https://www.npmjs.com/package/babel-plugin-angularjs-annotate) doesn't work with [Parcel bundler](https://github.com/parcel-bundler/parcel) with _implicit dependency injection annotations_, you need to make them _explicit_ by putting `/* @ngInject */` where needed and setting `"explicitOnly": true` option for the plugin.
Alternatively, you can use Webpack to make annotations implicit, but for this oppinionated starter I prefer Parcel, because it's faster, cleaner and allow to avoid the Webpack's configuration hell.
